repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    -   id: isort
        files: src/detector/
        args: ['--line-length', '120', '--profile', 'black']

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        files: src/detector/
        args: ['--line-length', '120']

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        files: src/detector/
        args: ['--max-line-length', '120', '--ignore', 'Q000,D100,D205,D212,D400,D415,W605']
